defaults:
  - _self_
  - experiments: null
  - func: null
  - override hydra/launcher: joblib

hydra:
  run:
    dir: multirun/${experiments.experiment_name}/  #${now:%Y-%m-%d-%H-%M-%S}
  sweep:
    dir: multirun/
    subdir: ${experiments.experiment_name}
print_config: True
seed: 87
test_size: .2