defaults:
  - _self_
  - dataset: null
  - experiments: null
  - func: null

hydra:
  run:
    dir: ./outputs/${experiments.model_name}/${experiments.datamodule.name}/${func}/${now:%Y-%m-%d}/${now:%H-%M-%S}
# run_dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
run_dir: ./outputs/${experiments.model_name}/${experiments.datamodule.name}/${func}/${now:%Y-%m-%d}/${now:%H-%M-%S}
print_config: True
seed: 87
test_size: .2
